name: bmi_calculator
description: BMI Calculator.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  shared_preferences: ^0.5.4+8
  url_launcher: ^5.2.7
  sqflite: ^1.1.7+3
  charts_flutter: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
